/**
 * Lotus Hub — SEO static file generator (Phase 7).
 *
 * Writes `public/robots.txt`, `public/sitemap.xml` and `public/llms.txt` from
 * environment configuration so canonical URLs always use the configured
 * production origin rather than a hard-coded development URL.
 *
 * Required public env: VITE_SITE_URL (e.g. https://lotus-hub.example).
 * Optional: VITE_APP_NAME, VITE_SITE_TAGLINE, VITE_SITE_DESCRIPTION.
 *
 * Run via `npm run seo:files` (also invoked automatically by `npm run build`).
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const outDir = path.join(ROOT, 'public')

// Load a light .env (never commit real values).
const env = { ...process.env }
try {
  const envPath = path.join(ROOT, '.env')
  if (fs.existsSync(envPath)) {
    for (const raw of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
      const line = raw.trim()
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq === -1) continue
      env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim()
    }
  }
} catch {
  /* ignore */
}

// Resolve the canonical origin. Only this domain is ever written to the files.
const configured = (env.VITE_SITE_URL || '').replace(/\/+$/, '')
const SITE_URL = configured || 'https://lotus-hub.example'

if (!configured) {
  console.warn(
    '[seo:files] VITE_SITE_URL is not set — writing placeholder origin https://lotus-hub.example. Set VITE_SITE_URL to the production domain before deploying.',
  )
}

const APP_NAME = env.VITE_APP_NAME || 'Lotus Hub'
const TAGLINE = env.VITE_SITE_TAGLINE || 'A premium media content discovery platform.'

// Public, indexable pages. Private/protected pages are deliberately excluded.
const PUBLIC_PAGES = [
  { path: '/faq', label: 'FAQ', desc: 'Frequently asked questions about Lotus Hub.' },
  { path: '/contact', label: 'Contact', desc: 'How to contact the Lotus Hub team.' },
  { path: '/terms', label: 'Terms of service', desc: 'Terms that govern your use of Lotus Hub.' },
  { path: '/privacy', label: 'Privacy policy', desc: 'How Lotus Hub handles your information.' },
  { path: '/cookies', label: 'Cookies policy', desc: 'How cookies are used on Lotus Hub.' },
]

const lastmod = new Date().toISOString().slice(0, 10)

// ---------------- robots.txt ----------------
const robots = `# ${APP_NAME} — robots.txt
# Generated by scripts/generate-seo.mjs from VITE_SITE_URL.
# robots.txt is a crawling hint, NOT an access-control mechanism. All private
# and protected pages still enforce authentication server-side.

User-agent: *
Allow: /

Disallow: /Admin/
Disallow: /browse
Disallow: /categories
Disallow: /file/
Disallow: /profile
Disallow: /tokens
Disallow: /login
Disallow: /register
Disallow: /session-expired
Disallow: /offline
Disallow: /error/
Disallow: /api/

Sitemap: ${SITE_URL}/sitemap.xml
`

// ---------------- sitemap.xml ----------------
const urlset = PUBLIC_PAGES.map(
  (p) => `  <url>
    <loc>${SITE_URL}${p.path}</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
    <lastmod>${lastmod}</lastmod>
  </url>`,
).join('\n')

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlset}
</urlset>
`

// ---------------- llms.txt ----------------
const pagesList = PUBLIC_PAGES.map((p) => `- [${p.label}](${SITE_URL}${p.path}): ${p.desc}`).join('\n')

const llms = `# ${APP_NAME}

> ${TAGLINE}

${APP_NAME} is a media content discovery platform that organizes films, images,
documents and audio into a clean library. This document describes only
information that is publicly available on the site.

Browsing the library, accounts, downloads, archive passwords, token balances,
purchase details and the admin console are private and require authentication;
they are not described here and are never exposed publicly.

## Public pages

${pagesList}

## Notes for AI agents

- The library and file listings are behind authentication and are not public.
- Do not assume any content, download destinations, passwords or user data are
  publicly accessible.
- All operational and contact details are configured by the project owner.
`

// ---------------- Write ----------------
fs.mkdirSync(outDir, { recursive: true })
const targets = [
  ['robots.txt', robots],
  ['sitemap.xml', sitemap],
  ['llms.txt', llms],
]
for (const [name, content] of targets) {
  fs.writeFileSync(path.join(outDir, name), content)
  console.log(`[seo:files] wrote public/${name}`)
}
